server:
    port: 8000

spring:
    application:
        name: cloud-order-consumer

eureka:
    client:
        # 表示将自己注册进EurekaServer
        register-with-eureka: true
        # 是否从EurekaServer抓取已有的注册信息 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
        fetch-registry: true
        service-url:
            # 单机
            # defaultZone: http://eureka7001.com:7001/eureka
            # 集群
            defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka