server:
    port: 9527

spring:
    application:
        name: cloud-gateway
    cloud:
        gateway:
            routes:
                - id: payment_routh  # 路由的id,唯一
                  uri: http://localhost:8001  # 匹配后提供服务的路由地址
                  predicates:
                      - Path=/payment/get/**  # 断言,路径相匹配的进行路由

                - id: payment_routh2
                  uri: http://localhost:8001
                  predicates:
                      - Path=/payment/port


eureka:
    instance:
        hostname: cloud-gateway-service
    client:
        # 表示将自己注册进EurekaServer
        register-with-eureka: true
        # 是否从EurekaServer抓取已有的注册信息 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
        fetch-registry: true
        service-url:
            # 单机
            defaultZone: http://eureka7001.com:7001/eureka
            # 集群
            # defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

